language: generic 
sudo: required
services: 
    - docker

before_install:
    - docker build -t mykhailohanol/angular-test -f ./fe/Dockerfile.dev ./fe

script:
    - docker run -e CI=true mykhailohanol/angular-test npm test

after_success: 
    - docker build -t mykhailohanol/multi-fe ./fe 
    - docker build -t mykhailohanol/multi-nginx ./nginx
    - docker build -t mykhailohanol/multi-server ./server
    - docker build -t mykhailohanol/multi-worker ./worker
    # Login into Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker Hub
    - docker push mykhailohanol/multi-fe 
    - docker push mykhailohanol/multi-nginx 
    - docker push mykhailohanol/multi-server 
    - docker push mykhailohanol/multi-worker 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-978828767084
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


