language: generic 
sudo: required
services: 
    - docker

before_install:
    - docker build -t mykhailohanol/angular-test -f ./fe/Dockerfile.dev ./fe

script:
    - docker run -e CI=true mykhailohanol/angular-test npm test

after_success: 
    - docker build -t mykhailohanol/multi-fe ./fe 
    - docker build -t mykhailohanol/multi-nginx ./nginx
    - docker build -t mykhailohanol/multi-server ./server
    - docker build -t mykhailohanol/multi-worker ./worker
    # Login into Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to Docker Hub
    - docker push mykhailohanol/multi-fe:latest
    - docker push mykhailohanol/multi-nginx:latest
    - docker push mykhailohanol/multi-server:latest
    - docker push mykhailohanol/multi-worker:latest

deploy:
    edge: true
    provider: elasticbeanstalk
    # the fastest way to take it from subdomain
    region: us-east-2
    app: multi-docker
    # Taken from elasticbeanstalk
    env: MultiDocker-env
    # Bucket name is taken from s3 (bucket created for the same area)
    bucket_name: elasticbeanstalk-us-east-2-978828767084 
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
